"""empty message

Revision ID: 785657a1454e
Revises: 4c67fbfd930a
Create Date: 2022-05-28 23:53:59.548293

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '785657a1454e'
down_revision = '4c67fbfd930a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('region_server')
    op.add_column('server', sa.Column('region_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'server', 'region', ['region_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'server', type_='foreignkey')
    op.drop_column('server', 'region_id')
    op.create_table('region_server',
    sa.Column('region_id', sa.INTEGER(), nullable=False),
    sa.Column('server_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['region_id'], ['region.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['server_id'], ['server.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('region_id', 'server_id')
    )
    # ### end Alembic commands ###
