"""change instance to storage

Revision ID: 7e58c846df00
Revises: 785657a1454e
Create Date: 2022-06-26 00:37:38.051847

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e58c846df00'
down_revision = '785657a1454e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('region', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_region_name'), ['name'])

    with op.batch_alter_table('server', schema=None) as batch_op:
        batch_op.add_column(sa.Column('storage', sa.Integer(), server_default='1', nullable=True))
        batch_op.create_unique_constraint(batch_op.f('uq_server_host'), ['host'])
        batch_op.create_foreign_key(batch_op.f('fk_server_region_id_region'), 'region', ['region_id'], ['id'])
        batch_op.drop_column('instance')

    with op.batch_alter_table('usage', schema=None) as batch_op:
        batch_op.add_column(sa.Column('storage_usage', sa.Integer(), server_default='1', nullable=False))
        batch_op.drop_column('instance_usage')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_user_email'), ['email'])
        batch_op.create_unique_constraint(batch_op.f('uq_user_name'), ['name'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_user_name'), type_='unique')
        batch_op.drop_constraint(batch_op.f('uq_user_email'), type_='unique')

    with op.batch_alter_table('usage', schema=None) as batch_op:
        batch_op.add_column(sa.Column('instance_usage', sa.INTEGER(), nullable=False))
        batch_op.drop_column('storage_usage')

    with op.batch_alter_table('server', schema=None) as batch_op:
        batch_op.add_column(sa.Column('instance', sa.INTEGER(), nullable=False))
        batch_op.drop_constraint(batch_op.f('fk_server_region_id_region'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('uq_server_host'), type_='unique')
        batch_op.drop_column('storage')

    with op.batch_alter_table('region', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_region_name'), type_='unique')

    # ### end Alembic commands ###
